
CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(100) UNIQUE NOT NULL,
  password_hash VARCHAR(256) NOT NULL
);

CREATE TABLE conversations (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id),
  query TEXT NOT NULL,
  reply TEXT NOT NULL,
  intent VARCHAR(64),
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
