databases:
  - name: chatbot-db
    databaseName: chatbot
    plan: starter

services:
  - type: web
    name: python-ai-service
    env: docker
    dockerfilePath: backend-python/Dockerfile
    autoDeploy: true
    healthCheckPath: /health
    plan: starter
    envVars:
      - key: AIzaSyBws4xBo1bGCF3Tecqc68FBP44VhcnYY7E
        sync: false
      - key: GEMINI_MODEL
        value: gemini-1.5-flash
      - key: HOST
        value: 0.0.0.0
      - key: ALLOWED_ORIGINS
        fromService:
          name: frontend
          property: url

  - type: web
    name: java-backend
    env: docker
    dockerfilePath: backend-java/Dockerfile
    autoDeploy: true
    healthCheckPath: /actuator/health
    plan: starter
    startCommand: >
      sh -c 'export SPRING_DATASOURCE_URL="jdbc:postgresql://$DB_HOST:$DB_PORT/$DB_NAME?sslmode=require";
      exec java $JAVA_OPTS -jar app.jar
      --server.port=$PORT
      --spring.datasource.url=$SPRING_DATASOURCE_URL
      --spring.datasource.username=$DB_USER
      --spring.datasource.password=$DB_PASSWORD'
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: chatbot-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: chatbot-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: chatbot-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: chatbot-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: chatbot-db
          property: password
      - key: AI_SERVICE_URL
        fromService:
          name: python-ai-service
          property: url
      - key: APP_CORS_ALLOWED_ORIGINS
        fromService:
          name: frontend
          property: url
      - key: JAVA_OPTS
        value: -XX:+UseZGC -XX:+UnlockExperimentalVMOptions -Xmx512m

  - type: web
    name: frontend
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    plan: starter
    envVars:
      - key: VITE_API_URL
        fromService:
          name: java-backend
          property: url